/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ee_nju_opencv_NativeMethod */

#ifndef _Included_ee_nju_opencv_NativeMethod
#define _Included_ee_nju_opencv_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ee_nju_opencv_NativeMethod
 * Method:    processFrame
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ee_nju_opencv_NativeMethod_processFrame
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
